---
language: bash

sudo: required
dist: trusty

before_install:
  - echo "deb http://archive.ubuntu.com/ubuntu/ wily universe" | sudo tee -a /etc/apt/sources.list
  - sudo apt-get update -qq
  - sudo apt-get install -y shellcheck

script:
  - find . -iname "*.sh" -exec shellcheck {} \;
